export { default as Albums } from './Albums/Albums'
export { default as Cover } from './Cover/Cover'
export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as List } from './List/List'
export { default as Logo } from './Logo/Logo'
export { default as Main } from './Main/Main'
export { default as Motto } from './Motto/Motto'
export { default as Preview } from './Preview/Preview'
export { default as Tab } from './Tab/Tab'
export { default as Tabs } from './Tabs/Tabs'
export { default as TempBurger } from './TempBurger/TempBurger'
export { default as TripItem } from './TripItem/TripItem'
export { TripsAlbums, tripsLoader } from './TripsAlbums/TripsAlbums'
export { default as YearItem } from './YearItem/YearItem'
