export { default as SvgFlagBelarus } from './SvgFlagBelarus'
export { default as SvgFooterHighlighter } from './SvgFooterHighlighter'
export { default as SvgMottoHighlighter } from './SvgMottoHighlighter'
export { default as SvgMountains } from './SvgMountains'
export { default as SvgTabsHighlighter } from './SvgTabsHighlighter'
export { default as SvgUnderline } from './SvgUnderline'
